#-------------------------------
# Site Settings

# Update site title and description for Horizon
title: Horizon
description: "Horizon is a movement dedicated to fostering peace, acceptance, and positive change."
logo: '/images/horizon-logo.png'

#-------------------------------
# Color Scheme Settings
color_scheme:
  default: light
  toggle: true

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Manifesto'
      url: '/manifesto/'
    - title: 'Join the Movement'
      url: '/join/'
    - title: 'Community'
      url: '/community/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: '/images/horizon-hero.jpg'
  hero_title: "Welcome to Horizon"
  hero_subtitle: "A New Dawn for Peace and Acceptance"
  hero_description: |
    Horizon is a community-driven movement committed to nurturing understanding, acceptance, and transformative change. 
    Together, we can build a future that embraces diversity, promotes peace, and fosters open dialogue.
  hero_image: '/images/horizon-hero-bg.jpg'
  hero_image_caption: "A new horizon for humanity."
  hero_button_text: "Join the Movement"
  hero_button_link: '/join/'

#-------------------------------
# Footer Settings
footer_description: "Horizon is about fostering positive change, acceptance, and unity. Join us as we strive to make a difference in the world."

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-reddit-alien", name: "Reddit", link: "https://reddit.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}

#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com
  button_text: "Send Message"

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
